title: Steradian Gallery
description: A Virtual Gallery experience for the HTC Vive
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

downloadPage: downloadPage
issues_url: https://github.com/twidgelab/SteradianGallery_docs/issues
zip_url: https://github.com/twidgelab/SteradianGallery_docs/releases/download/v0.1.1/SteradianGallery.0.1.1.zip

gems:
  - jemoji
